// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakip.API.Data;

#nullable disable

namespace StokTakip.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("StokTakip.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elektronik ürünler",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giyim ürünleri",
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gıda ürünleri",
                            Name = "Gıda"
                        });
                });

            modelBuilder.Entity("StokTakip.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            MinStockLevel = 3,
                            Name = "Laptop",
                            Price = 25000m,
                            SKU = "ELK-001",
                            StockQuantity = 10,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            MinStockLevel = 5,
                            Name = "Kulaklık",
                            Price = 1500m,
                            SKU = "ELK-002",
                            StockQuantity = 2,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            MinStockLevel = 10,
                            Name = "T-Shirt",
                            Price = 250m,
                            SKU = "GIY-001",
                            StockQuantity = 50,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("StokTakip.API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "Ali Yılmaz",
                            Email = "ali@techsupply.com",
                            Name = "TechSupply A.Ş.",
                            Phone = "0212 111 22 33"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "Ayşe Kaya",
                            Email = "ayse@modagroup.com",
                            Name = "ModaGroup Ltd.",
                            Phone = "0212 444 55 66"
                        });
                });

            modelBuilder.Entity("StokTakip.API.Models.Product", b =>
                {
                    b.HasOne("StokTakip.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakip.API.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StokTakip.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StokTakip.API.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
